# Generated by Django 4.0 on 2021-12-23 13:23

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('slug', models.SlugField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, max_length=300, unique=True)),
                ('thumbnail', pyuploadcare.dj.models.ImageField(blank=True)),
                ('snippet', models.TextField(blank=True, max_length=255)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('published', models.BooleanField(db_index=True, default=True)),
                ('post_date', models.DateField(auto_now_add=True)),
                ('post_time', models.DateTimeField(auto_now_add=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='blog_post', to='posts.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Anonymous', max_length=1000)),
                ('email', models.EmailField(blank=True, max_length=1000)),
                ('body', models.TextField(max_length=1000)),
                ('post_date', models.DateField(auto_now_add=True)),
                ('post_time', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='posts.comment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.post')),
            ],
            options={
                'ordering': ('-post_time',),
            },
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['slug', 'published'], name='posts_post_slug_0bc1c5_idx'),
        ),
    ]
