# Generated by Django 4.0 on 2021-12-31 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_related_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='meta_keywords',
            field=models.CharField(default='Coding, Blog Post, SoftLab, Tutorial', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='premium',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='related_posts',
            field=models.ManyToManyField(blank=True, null=True, to='posts.Post'),
        ),
    ]
