# Generated by Django 4.0 on 2022-04-07 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_comment_posts_comme_active_77e66b_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
