# Generated by Django 4.0 on 2022-04-07 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_tag_post_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
    ]
