# Generated by Django 4.0 on 2022-04-08 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_post_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='related_posts',
        ),
    ]
