# Generated by Django 4.0 on 2021-12-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='newsletter_subscribed',
            field=models.BooleanField(default=True),
        ),
    ]
