# Generated by Django 4.0 on 2021-12-23 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_newsletter_subscribed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='newsletter_subscribed',
        ),
    ]
